mega_items={
    "Abomasite": ("Abomasnow", "Abomasnow-Mega"),
    "Absolite": ("Absol", "Absol-Mega"),
    "Aerodactylite": ("Aerodactyl", "Aerodactyl-Mega"),
    "Aggronite": ("Aggron", "Aggron-Mega"),
    "Alakazite": ("Alakazam", "Alakazam-Mega"),
    "Altarianite": ("Altaria", "Altaria-Mega"),
    "Ampharosite": ("Ampharos", "Ampharos-Mega"),
    "Audinite": ("Audino", "Audino-Mega"),
    "Banettite": ("Banette", "Banette-Mega"),
    "Beedrillite": ("Beedrill", "Beedrill-Mega"),
    "Blastoisinite": ("Blastoise", "Blastoise-Mega"),
    "Blazikenite": ("Blaziken", "Blaziken-Mega"),
    "Cameruptite": ("Camerupt", "Camerupt-Mega"),
    "Charizardite Y": ("Charizard", "Charizard-Mega-Y"),
    "Charizardite X": ("Charizard", "Charizard-Mega-X"),
    "Diancite": ("Diancie", "Diancie-Mega"),
    "Galladite": ("Gallade", "Gallade-Mega"),
    "Garchompite": ("Garchomp", "Garchomp-Mega"),
    "Gardevoirite": ("Gardevoir", "Gardevoir-Mega"),
    "Gengarite": ("Gengar", "Gengar-Mega"),
    "Glalitite": ("Glalie", "Glalie-Mega"),
    "Gyaradosite": ("Gyarados", "Gyarados-Mega"),
    "Heracronite": ("Heracross", "Heracross-Mega"),
    "Houndoominite": ("Houndoom", "Houndoom-Mega"),
    "Kangaskhanite": ("Kangaskhan", "Kangaskhan-Mega"),
    "Latiasite": ("Latias", "Latias-Mega"),
    "Latiosite": ("Latios", "Latios-Mega"),
    "Lopunnite": ("Lopunny", "Lopunny-Mega"),
    "Lucarionite": ("Lucario", "Lucario-Mega"),
    "Manectite": ("Manectric", "Manectric-Mega"),
    "Mawilite": ("Mawile", "Mawile-Mega"),
    "Medichamite": ("Medicham", "Medicham-Mega"),
    "Metagrossite": ("Metagross", "Metagross-Mega"),
    "Mewtwonite X": ("Mewtwo", "Mewtwo-Mega-X"),
    "Mewtwonite Y": ("Mewtwo", "Mewtwo-Mega-Y"),
    "Pidgeotite": ("Pidgeot", "Pidgeot-Mega"),
    "Pinsirite": ("Pinsir", "Pinsir-Mega"),
    "Rayquaza": ("Rayquaza", "Rayquaza-Mega"),
    "Sablenite": ("Sableye", "Sableye-Mega"),
    "Salamencite": ("Salamence", "Salamence-Mega"),
    "Sceptilite": ("Sceptile", "Sceptile-Mega"),
    "Scizorite": ("Scizor", "Scizor-Mega"),
    "Sharpedonite": ("Sharpedo", "Sharpedo-Mega"),
    "Slowbronite": ("Slowbro", "Slowbro-Mega"),
    "Steelixite": ("Steelix", "Steelix-Mega"),
    "Swampertite": ("Swampert", "Swampert-Mega"),
    "Tyranitarite": ("Tyranitar", "Tyranitar-Mega"),
    "Venusaurite": ("Venusaur", "Venusaur-Mega"),
}
