from moves import DamagingMove
moves = {
    "Absorb": DamagingMove("Absorb",
                              power=20,
                              category="Special",
                              type="Grass"),
    "Acid": DamagingMove("Acid",
                              power=40,
                              category="Special",
                              type="Poison"),
    "Acid Spray": DamagingMove("Acid Spray",
                              power=40,
                              category="Special",
                              type="Poison"),
    "Acrobatics": DamagingMove("Acrobatics",
                              power=55,
                              category="Physical",
                              type="Flying"),
    "Aerial Ace": DamagingMove("Aerial Ace",
                              power=60,
                              category="Physical",
                              type="Flying"),
    "Aeroblast": DamagingMove("Aeroblast",
                              power=100,
                              category="Special",
                              type="Flying"),
    "Air Cutter": DamagingMove("Air Cutter",
                              power=60,
                              category="Special",
                              type="Flying"),
    "Air Slash": DamagingMove("Air Slash",
                              power=75,
                              category="Special",
                              type="Flying"),
    "Ancient Power": DamagingMove("Ancient Power",
                              power=60,
                              category="Special",
                              type="Rock"),
    "Aqua Jet": DamagingMove("Aqua Jet",
                              power=40,
                              category="Physical",
                              type="Water"),
    "Aqua Tail": DamagingMove("Aqua Tail",
                              power=90,
                              category="Physical",
                              type="Water"),
    "Arm Thrust": DamagingMove("Arm Thrust",
                              power=15,
                              category="Physical",
                              type="Fighting"),
    "Assurance": DamagingMove("Assurance",
                              power=60,
                              category="Physical",
                              type="Dark"),
    "Astonish": DamagingMove("Astonish",
                              power=30,
                              category="Physical",
                              type="Ghost"),
    "Attack Order": DamagingMove("Attack Order",
                              power=90,
                              category="Physical",
                              type="Bug"),
    "Aura Sphere": DamagingMove("Aura Sphere",
                              power=80,
                              category="Special",
                              type="Fighting"),
    "Aurora Beam": DamagingMove("Aurora Beam",
                              power=65,
                              category="Special",
                              type="Ice"),
    "Avalanche": DamagingMove("Avalanche",
                              power=60,
                              category="Physical",
                              type="Ice"),
    "Barrage": DamagingMove("Barrage",
                              power=15,
                              category="Physical",
                              type="Normal"),
    "Beat Up": DamagingMove("Beat Up",
                              power=0,
                              category="Physical",
                              type="Dark"),
    "Belch": DamagingMove("Belch",
                              power=120,
                              category="Special",
                              type="Poison"),
    "Bide": DamagingMove("Bide",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Bind": DamagingMove("Bind",
                              power=15,
                              category="Physical",
                              type="Normal"),
    "Bite": DamagingMove("Bite",
                              power=60,
                              category="Physical",
                              type="Dark"),
    "Blast Burn": DamagingMove("Blast Burn",
                              power=150,
                              category="Special",
                              type="Fire"),
    "Blaze Kick": DamagingMove("Blaze Kick",
                              power=85,
                              category="Physical",
                              type="Fire"),
    "Blizzard": DamagingMove("Blizzard",
                              power=110,
                              category="Special",
                              type="Ice"),
    "Blue Flare": DamagingMove("Blue Flare",
                              power=130,
                              category="Special",
                              type="Fire"),
    "Body Slam": DamagingMove("Body Slam",
                              power=85,
                              category="Physical",
                              type="Normal"),
    "Bolt Strike": DamagingMove("Bolt Strike",
                              power=130,
                              category="Physical",
                              type="Electric"),
    "Bone Club": DamagingMove("Bone Club",
                              power=65,
                              category="Physical",
                              type="Ground"),
    "Bone Rush": DamagingMove("Bone Rush",
                              power=25,
                              category="Physical",
                              type="Ground"),
    "Bonemerang": DamagingMove("Bonemerang",
                              power=50,
                              category="Physical",
                              type="Ground"),
    "Boomburst": DamagingMove("Boomburst",
                              power=140,
                              category="Special",
                              type="Normal"),
    "Bounce": DamagingMove("Bounce",
                              power=85,
                              category="Physical",
                              type="Flying"),
    "Brave Bird": DamagingMove("Brave Bird",
                              power=120,
                              category="Physical",
                              type="Flying"),
    "Brick Break": DamagingMove("Brick Break",
                              power=75,
                              category="Physical",
                              type="Fighting"),
    "Brine": DamagingMove("Brine",
                              power=65,
                              category="Special",
                              type="Water"),
    "Bubble": DamagingMove("Bubble",
                              power=40,
                              category="Special",
                              type="Water"),
    "Bubble Beam": DamagingMove("Bubble Beam",
                              power=65,
                              category="Special",
                              type="Water"),
    "Bug Bite": DamagingMove("Bug Bite",
                              power=60,
                              category="Physical",
                              type="Bug"),
    "Bug Buzz": DamagingMove("Bug Buzz",
                              power=90,
                              category="Special",
                              type="Bug"),
    "Bulldoze": DamagingMove("Bulldoze",
                              power=60,
                              category="Physical",
                              type="Ground"),
    "Bullet Punch": DamagingMove("Bullet Punch",
                              power=40,
                              category="Physical",
                              type="Steel"),
    "Bullet Seed": DamagingMove("Bullet Seed",
                              power=25,
                              category="Physical",
                              type="Grass"),
    "Charge Beam": DamagingMove("Charge Beam",
                              power=50,
                              category="Special",
                              type="Electric"),
    "Chatter": DamagingMove("Chatter",
                              power=65,
                              category="Special",
                              type="Flying"),
    "Chip Away": DamagingMove("Chip Away",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Circle Throw": DamagingMove("Circle Throw",
                              power=60,
                              category="Physical",
                              type="Fighting"),
    "Clamp": DamagingMove("Clamp",
                              power=35,
                              category="Physical",
                              type="Water"),
    "Clear Smog": DamagingMove("Clear Smog",
                              power=50,
                              category="Special",
                              type="Poison"),
    "Close Combat": DamagingMove("Close Combat",
                              power=120,
                              category="Physical",
                              type="Fighting"),
    "Comet Punch": DamagingMove("Comet Punch",
                              power=18,
                              category="Physical",
                              type="Normal"),
    "Confusion": DamagingMove("Confusion",
                              power=50,
                              category="Special",
                              type="Psychic"),
    "Constrict": DamagingMove("Constrict",
                              power=10,
                              category="Physical",
                              type="Normal"),
    "Counter": DamagingMove("Counter",
                              power=0,
                              category="Physical",
                              type="Fighting"),
    "Covet": DamagingMove("Covet",
                              power=60,
                              category="Physical",
                              type="Normal"),
    "Crabhammer": DamagingMove("Crabhammer",
                              power=100,
                              category="Physical",
                              type="Water"),
    "Cross Chop": DamagingMove("Cross Chop",
                              power=100,
                              category="Physical",
                              type="Fighting"),
    "Cross Poison": DamagingMove("Cross Poison",
                              power=70,
                              category="Physical",
                              type="Poison"),
    "Crunch": DamagingMove("Crunch",
                              power=80,
                              category="Physical",
                              type="Dark"),
    "Crush Claw": DamagingMove("Crush Claw",
                              power=75,
                              category="Physical",
                              type="Normal"),
    "Crush Grip": DamagingMove("Crush Grip",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Cut": DamagingMove("Cut",
                              power=50,
                              category="Physical",
                              type="Normal"),
    "Dark Pulse": DamagingMove("Dark Pulse",
                              power=80,
                              category="Special",
                              type="Dark"),
    "Dazzling Gleam": DamagingMove("Dazzling Gleam",
                              power=80,
                              category="Special",
                              type="Fairy"),
    "Diamond Storm": DamagingMove("Diamond Storm",
                              power=100,
                              category="Physical",
                              type="Rock"),
    "Dig": DamagingMove("Dig",
                              power=80,
                              category="Physical",
                              type="Ground"),
    "Disarming Voice": DamagingMove("Disarming Voice",
                              power=40,
                              category="Special",
                              type="Fairy"),
    "Discharge": DamagingMove("Discharge",
                              power=80,
                              category="Special",
                              type="Electric"),
    "Dive": DamagingMove("Dive",
                              power=80,
                              category="Physical",
                              type="Water"),
    "Dizzy Punch": DamagingMove("Dizzy Punch",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Doom Desire": DamagingMove("Doom Desire",
                              power=140,
                              category="Special",
                              type="Steel"),
    "Double Hit": DamagingMove("Double Hit",
                              power=35,
                              category="Physical",
                              type="Normal"),
    "Double Kick": DamagingMove("Double Kick",
                              power=30,
                              category="Physical",
                              type="Fighting"),
    "Double Slap": DamagingMove("Double Slap",
                              power=15,
                              category="Physical",
                              type="Normal"),
    "Double-Edge": DamagingMove("Double-Edge",
                              power=120,
                              category="Physical",
                              type="Normal"),
    "Draco Meteor": DamagingMove("Draco Meteor",
                              power=130,
                              category="Special",
                              type="Dragon"),
    "Dragon Ascent": DamagingMove("Dragon Ascent",
                              power=120,
                              category="Physical",
                              type="Flying"),
    "Dragon Breath": DamagingMove("Dragon Breath",
                              power=60,
                              category="Special",
                              type="Dragon"),
    "Dragon Claw": DamagingMove("Dragon Claw",
                              power=80,
                              category="Physical",
                              type="Dragon"),
    "Dragon Pulse": DamagingMove("Dragon Pulse",
                              power=85,
                              category="Special",
                              type="Dragon"),
    "Dragon Rage": DamagingMove("Dragon Rage",
                              power=0,
                              category="Special",
                              type="Dragon"),
    "Dragon Rush": DamagingMove("Dragon Rush",
                              power=100,
                              category="Physical",
                              type="Dragon"),
    "Dragon Tail": DamagingMove("Dragon Tail",
                              power=60,
                              category="Physical",
                              type="Dragon"),
    "Drain Punch": DamagingMove("Drain Punch",
                              power=75,
                              category="Physical",
                              type="Fighting"),
    "Draining Kiss": DamagingMove("Draining Kiss",
                              power=50,
                              category="Special",
                              type="Fairy"),
    "Dream Eater": DamagingMove("Dream Eater",
                              power=100,
                              category="Special",
                              type="Psychic"),
    "Drill Peck": DamagingMove("Drill Peck",
                              power=80,
                              category="Physical",
                              type="Flying"),
    "Drill Run": DamagingMove("Drill Run",
                              power=80,
                              category="Physical",
                              type="Ground"),
    "Dual Chop": DamagingMove("Dual Chop",
                              power=40,
                              category="Physical",
                              type="Dragon"),
    "Dynamic Punch": DamagingMove("Dynamic Punch",
                              power=100,
                              category="Physical",
                              type="Fighting"),
    "Earth Power": DamagingMove("Earth Power",
                              power=90,
                              category="Special",
                              type="Ground"),
    "Earthquake": DamagingMove("Earthquake",
                              power=100,
                              category="Physical",
                              type="Ground"),
    "Echoed Voice": DamagingMove("Echoed Voice",
                              power=40,
                              category="Special",
                              type="Normal"),
    "Egg Bomb": DamagingMove("Egg Bomb",
                              power=100,
                              category="Physical",
                              type="Normal"),
    "Electro Ball": DamagingMove("Electro Ball",
                              power=0,
                              category="Special",
                              type="Electric"),
    "Electroweb": DamagingMove("Electroweb",
                              power=55,
                              category="Special",
                              type="Electric"),
    "Ember": DamagingMove("Ember",
                              power=40,
                              category="Special",
                              type="Fire"),
    "Endeavor": DamagingMove("Endeavor",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Energy Ball": DamagingMove("Energy Ball",
                              power=90,
                              category="Special",
                              type="Grass"),
    "Eruption": DamagingMove("Eruption",
                              power=150,
                              category="Special",
                              type="Fire"),
    "Explosion": DamagingMove("Explosion",
                              power=250,
                              category="Physical",
                              type="Normal"),
    "Extrasensory": DamagingMove("Extrasensory",
                              power=80,
                              category="Special",
                              type="Psychic"),
    "Extreme Speed": DamagingMove("Extreme Speed",
                              power=80,
                              category="Physical",
                              type="Normal"),
    "Facade": DamagingMove("Facade",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Fairy Wind": DamagingMove("Fairy Wind",
                              power=40,
                              category="Special",
                              type="Fairy"),
    "Fake Out": DamagingMove("Fake Out",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "False Swipe": DamagingMove("False Swipe",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Feint": DamagingMove("Feint",
                              power=30,
                              category="Physical",
                              type="Normal"),
    "Feint Attack": DamagingMove("Feint Attack",
                              power=60,
                              category="Physical",
                              type="Dark"),
    "Fell Stinger": DamagingMove("Fell Stinger",
                              power=30,
                              category="Physical",
                              type="Bug"),
    "Fiery Dance": DamagingMove("Fiery Dance",
                              power=80,
                              category="Special",
                              type="Fire"),
    "Final Gambit": DamagingMove("Final Gambit",
                              power=0,
                              category="Special",
                              type="Fighting"),
    "Fire Blast": DamagingMove("Fire Blast",
                              power=110,
                              category="Special",
                              type="Fire"),
    "Fire Fang": DamagingMove("Fire Fang",
                              power=65,
                              category="Physical",
                              type="Fire"),
    "Fire Pledge": DamagingMove("Fire Pledge",
                              power=80,
                              category="Special",
                              type="Fire"),
    "Fire Punch": DamagingMove("Fire Punch",
                              power=75,
                              category="Physical",
                              type="Fire"),
    "Fire Spin": DamagingMove("Fire Spin",
                              power=35,
                              category="Special",
                              type="Fire"),
    "Fissure": DamagingMove("Fissure",
                              power=0,
                              category="Physical",
                              type="Ground"),
    "Flail": DamagingMove("Flail",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Flame Burst": DamagingMove("Flame Burst",
                              power=70,
                              category="Special",
                              type="Fire"),
    "Flame Charge": DamagingMove("Flame Charge",
                              power=50,
                              category="Physical",
                              type="Fire"),
    "Flame Wheel": DamagingMove("Flame Wheel",
                              power=60,
                              category="Physical",
                              type="Fire"),
    "Flamethrower": DamagingMove("Flamethrower",
                              power=90,
                              category="Special",
                              type="Fire"),
    "Flare Blitz": DamagingMove("Flare Blitz",
                              power=120,
                              category="Physical",
                              type="Fire"),
    "Flash Cannon": DamagingMove("Flash Cannon",
                              power=80,
                              category="Special",
                              type="Steel"),
    "Fling": DamagingMove("Fling",
                              power=0,
                              category="Physical",
                              type="Dark"),
    "Fly": DamagingMove("Fly",
                              power=90,
                              category="Physical",
                              type="Flying"),
    "Flying Press": DamagingMove("Flying Press",
                              power=80,
                              category="Physical",
                              type="Fighting"),
    "Focus Blast": DamagingMove("Focus Blast",
                              power=120,
                              category="Special",
                              type="Fighting"),
    "Focus Punch": DamagingMove("Focus Punch",
                              power=150,
                              category="Physical",
                              type="Fighting"),
    "Force Palm": DamagingMove("Force Palm",
                              power=60,
                              category="Physical",
                              type="Fighting"),
    "Foul Play": DamagingMove("Foul Play",
                              power=95,
                              category="Physical",
                              type="Dark"),
    "Freeze Shock": DamagingMove("Freeze Shock",
                              power=140,
                              category="Physical",
                              type="Ice"),
    "Freeze-Dry": DamagingMove("Freeze-Dry",
                              power=70,
                              category="Special",
                              type="Ice"),
    "Frenzy Plant": DamagingMove("Frenzy Plant",
                              power=150,
                              category="Special",
                              type="Grass"),
    "Frost Breath": DamagingMove("Frost Breath",
                              power=60,
                              category="Special",
                              type="Ice"),
    "Frustration": DamagingMove("Frustration",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Fury Attack": DamagingMove("Fury Attack",
                              power=15,
                              category="Physical",
                              type="Normal"),
    "Fury Cutter": DamagingMove("Fury Cutter",
                              power=40,
                              category="Physical",
                              type="Bug"),
    "Fury Swipes": DamagingMove("Fury Swipes",
                              power=18,
                              category="Physical",
                              type="Normal"),
    "Fusion Bolt": DamagingMove("Fusion Bolt",
                              power=100,
                              category="Physical",
                              type="Electric"),
    "Fusion Flare": DamagingMove("Fusion Flare",
                              power=100,
                              category="Special",
                              type="Fire"),
    "Future Sight": DamagingMove("Future Sight",
                              power=120,
                              category="Special",
                              type="Psychic"),
    "Gear Grind": DamagingMove("Gear Grind",
                              power=50,
                              category="Physical",
                              type="Steel"),
    "Giga Drain": DamagingMove("Giga Drain",
                              power=75,
                              category="Special",
                              type="Grass"),
    "Giga Impact": DamagingMove("Giga Impact",
                              power=150,
                              category="Physical",
                              type="Normal"),
    "Glaciate": DamagingMove("Glaciate",
                              power=65,
                              category="Special",
                              type="Ice"),
    "Grass Knot": DamagingMove("Grass Knot",
                              power=0,
                              category="Special",
                              type="Grass"),
    "Grass Pledge": DamagingMove("Grass Pledge",
                              power=80,
                              category="Special",
                              type="Grass"),
    "Guillotine": DamagingMove("Guillotine",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Gunk Shot": DamagingMove("Gunk Shot",
                              power=120,
                              category="Physical",
                              type="Poison"),
    "Gust": DamagingMove("Gust",
                              power=40,
                              category="Special",
                              type="Flying"),
    "Gyro Ball": DamagingMove("Gyro Ball",
                              power=0,
                              category="Physical",
                              type="Steel"),
    "Hammer Arm": DamagingMove("Hammer Arm",
                              power=100,
                              category="Physical",
                              type="Fighting"),
    "Head Charge": DamagingMove("Head Charge",
                              power=120,
                              category="Physical",
                              type="Normal"),
    "Head Smash": DamagingMove("Head Smash",
                              power=150,
                              category="Physical",
                              type="Rock"),
    "Headbutt": DamagingMove("Headbutt",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Heart Stamp": DamagingMove("Heart Stamp",
                              power=60,
                              category="Physical",
                              type="Psychic"),
    "Heat Crash": DamagingMove("Heat Crash",
                              power=0,
                              category="Physical",
                              type="Fire"),
    "Heat Wave": DamagingMove("Heat Wave",
                              power=95,
                              category="Special",
                              type="Fire"),
    "Heavy Slam": DamagingMove("Heavy Slam",
                              power=0,
                              category="Physical",
                              type="Steel"),
    "Hex": DamagingMove("Hex",
                              power=65,
                              category="Special",
                              type="Ghost"),
    "Hidden Power Bug": DamagingMove("Hidden Power Bug",
                              power=60,
                              category="Special",
                              type="Bug"),
    "Hidden Power Dark": DamagingMove("Hidden Power Dark",
                              power=60,
                              category="Special",
                              type="Dark"),
    "Hidden Power Dragon": DamagingMove("Hidden Power Dragon",
                              power=60,
                              category="Special",
                              type="Dragon"),
    "Hidden Power Electric": DamagingMove("Hidden Power Electric",
                              power=60,
                              category="Special",
                              type="Electric"),
    "Hidden Power Fighting": DamagingMove("Hidden Power Fighting",
                              power=60,
                              category="Special",
                              type="Fighting"),
    "Hidden Power Fire": DamagingMove("Hidden Power Fire",
                              power=60,
                              category="Special",
                              type="Fire"),
    "Hidden Power Flying": DamagingMove("Hidden Power Flying",
                              power=60,
                              category="Special",
                              type="Flying"),
    "Hidden Power Ghost": DamagingMove("Hidden Power Ghost",
                              power=60,
                              category="Special",
                              type="Ghost"),
    "Hidden Power Grass": DamagingMove("Hidden Power Grass",
                              power=60,
                              category="Special",
                              type="Grass"),
    "Hidden Power Ground": DamagingMove("Hidden Power Ground",
                              power=60,
                              category="Special",
                              type="Ground"),
    "Hidden Power Ice": DamagingMove("Hidden Power Ice",
                              power=60,
                              category="Special",
                              type="Ice"),
    "Hidden Power Poison": DamagingMove("Hidden Power Poison",
                              power=60,
                              category="Special",
                              type="Poison"),
    "Hidden Power Psychic": DamagingMove("Hidden Power Psychic",
                              power=60,
                              category="Special",
                              type="Psychic"),
    "Hidden Power Rock": DamagingMove("Hidden Power Rock",
                              power=60,
                              category="Special",
                              type="Rock"),
    "Hidden Power Steel": DamagingMove("Hidden Power Steel",
                              power=60,
                              category="Special",
                              type="Steel"),
    "Hidden Power Water": DamagingMove("Hidden Power Water",
                              power=60,
                              category="Special",
                              type="Water"),
    "High Jump Kick": DamagingMove("High Jump Kick",
                              power=130,
                              category="Physical",
                              type="Fighting"),
    "Hold Back": DamagingMove("Hold Back",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Horn Attack": DamagingMove("Horn Attack",
                              power=65,
                              category="Physical",
                              type="Normal"),
    "Horn Drill": DamagingMove("Horn Drill",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Horn Leech": DamagingMove("Horn Leech",
                              power=75,
                              category="Physical",
                              type="Grass"),
    "Hurricane": DamagingMove("Hurricane",
                              power=110,
                              category="Special",
                              type="Flying"),
    "Hydro Cannon": DamagingMove("Hydro Cannon",
                              power=150,
                              category="Special",
                              type="Water"),
    "Hydro Pump": DamagingMove("Hydro Pump",
                              power=110,
                              category="Special",
                              type="Water"),
    "Hyper Beam": DamagingMove("Hyper Beam",
                              power=150,
                              category="Special",
                              type="Normal"),
    "Hyper Fang": DamagingMove("Hyper Fang",
                              power=80,
                              category="Physical",
                              type="Normal"),
    "Hyper Voice": DamagingMove("Hyper Voice",
                              power=90,
                              category="Special",
                              type="Normal"),
    "Hyperspace Fury": DamagingMove("Hyperspace Fury",
                              power=100,
                              category="Special",
                              type="Dark"),
    "Hyperspace Hole": DamagingMove("Hyperspace Hole",
                              power=80,
                              category="Special",
                              type="Psychic"),
    "Ice Ball": DamagingMove("Ice Ball",
                              power=30,
                              category="Physical",
                              type="Ice"),
    "Ice Beam": DamagingMove("Ice Beam",
                              power=90,
                              category="Special",
                              type="Ice"),
    "Ice Burn": DamagingMove("Ice Burn",
                              power=140,
                              category="Special",
                              type="Ice"),
    "Ice Fang": DamagingMove("Ice Fang",
                              power=65,
                              category="Physical",
                              type="Ice"),
    "Ice Punch": DamagingMove("Ice Punch",
                              power=75,
                              category="Physical",
                              type="Ice"),
    "Ice Shard": DamagingMove("Ice Shard",
                              power=40,
                              category="Physical",
                              type="Ice"),
    "Icicle Crash": DamagingMove("Icicle Crash",
                              power=85,
                              category="Physical",
                              type="Ice"),
    "Icicle Spear": DamagingMove("Icicle Spear",
                              power=25,
                              category="Physical",
                              type="Ice"),
    "Icy Wind": DamagingMove("Icy Wind",
                              power=55,
                              category="Special",
                              type="Ice"),
    "Incinerate": DamagingMove("Incinerate",
                              power=60,
                              category="Special",
                              type="Fire"),
    "Inferno": DamagingMove("Inferno",
                              power=100,
                              category="Special",
                              type="Fire"),
    "Infestation": DamagingMove("Infestation",
                              power=20,
                              category="Special",
                              type="Bug"),
    "Iron Head": DamagingMove("Iron Head",
                              power=80,
                              category="Physical",
                              type="Steel"),
    "Iron Tail": DamagingMove("Iron Tail",
                              power=100,
                              category="Physical",
                              type="Steel"),
    "Judgment": DamagingMove("Judgment",
                              power=100,
                              category="Special",
                              type="Normal"),
    "Jump Kick": DamagingMove("Jump Kick",
                              power=100,
                              category="Physical",
                              type="Fighting"),
    "Karate Chop": DamagingMove("Karate Chop",
                              power=50,
                              category="Physical",
                              type="Fighting"),
    "Knock Off": DamagingMove("Knock Off",
                              power=65,
                              category="Physical",
                              type="Dark"),
    "Land's Wrath": DamagingMove("Land's Wrath",
                              power=90,
                              category="Physical",
                              type="Ground"),
    "Last Resort": DamagingMove("Last Resort",
                              power=140,
                              category="Physical",
                              type="Normal"),
    "Lava Plume": DamagingMove("Lava Plume",
                              power=80,
                              category="Special",
                              type="Fire"),
    "Leaf Blade": DamagingMove("Leaf Blade",
                              power=90,
                              category="Physical",
                              type="Grass"),
    "Leaf Storm": DamagingMove("Leaf Storm",
                              power=130,
                              category="Special",
                              type="Grass"),
    "Leaf Tornado": DamagingMove("Leaf Tornado",
                              power=65,
                              category="Special",
                              type="Grass"),
    "Leech Life": DamagingMove("Leech Life",
                              power=20,
                              category="Physical",
                              type="Bug"),
    "Lick": DamagingMove("Lick",
                              power=30,
                              category="Physical",
                              type="Ghost"),
    "Light of Ruin": DamagingMove("Light of Ruin",
                              power=140,
                              category="Special",
                              type="Fairy"),
    "Low Kick": DamagingMove("Low Kick",
                              power=0,
                              category="Physical",
                              type="Fighting"),
    "Low Sweep": DamagingMove("Low Sweep",
                              power=65,
                              category="Physical",
                              type="Fighting"),
    "Luster Purge": DamagingMove("Luster Purge",
                              power=70,
                              category="Special",
                              type="Psychic"),
    "Mach Punch": DamagingMove("Mach Punch",
                              power=40,
                              category="Physical",
                              type="Fighting"),
    "Magical Leaf": DamagingMove("Magical Leaf",
                              power=60,
                              category="Special",
                              type="Grass"),
    "Magma Storm": DamagingMove("Magma Storm",
                              power=100,
                              category="Special",
                              type="Fire"),
    "Magnet Bomb": DamagingMove("Magnet Bomb",
                              power=60,
                              category="Physical",
                              type="Steel"),
    "Magnitude": DamagingMove("Magnitude",
                              power=0,
                              category="Physical",
                              type="Ground"),
    "Mega Drain": DamagingMove("Mega Drain",
                              power=40,
                              category="Special",
                              type="Grass"),
    "Mega Kick": DamagingMove("Mega Kick",
                              power=120,
                              category="Physical",
                              type="Normal"),
    "Mega Punch": DamagingMove("Mega Punch",
                              power=80,
                              category="Physical",
                              type="Normal"),
    "Megahorn": DamagingMove("Megahorn",
                              power=120,
                              category="Physical",
                              type="Bug"),
    "Metal Burst": DamagingMove("Metal Burst",
                              power=0,
                              category="Physical",
                              type="Steel"),
    "Metal Claw": DamagingMove("Metal Claw",
                              power=50,
                              category="Physical",
                              type="Steel"),
    "Meteor Mash": DamagingMove("Meteor Mash",
                              power=90,
                              category="Physical",
                              type="Steel"),
    "Mirror Coat": DamagingMove("Mirror Coat",
                              power=0,
                              category="Special",
                              type="Psychic"),
    "Mirror Shot": DamagingMove("Mirror Shot",
                              power=65,
                              category="Special",
                              type="Steel"),
    "Mist Ball": DamagingMove("Mist Ball",
                              power=70,
                              category="Special",
                              type="Psychic"),
    "Moonblast": DamagingMove("Moonblast",
                              power=95,
                              category="Special",
                              type="Fairy"),
    "Mud Bomb": DamagingMove("Mud Bomb",
                              power=65,
                              category="Special",
                              type="Ground"),
    "Mud Shot": DamagingMove("Mud Shot",
                              power=55,
                              category="Special",
                              type="Ground"),
    "Mud-Slap": DamagingMove("Mud-Slap",
                              power=20,
                              category="Special",
                              type="Ground"),
    "Muddy Water": DamagingMove("Muddy Water",
                              power=90,
                              category="Special",
                              type="Water"),
    "Mystical Fire": DamagingMove("Mystical Fire",
                              power=65,
                              category="Special",
                              type="Fire"),
    "Natural Gift": DamagingMove("Natural Gift",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Needle Arm": DamagingMove("Needle Arm",
                              power=60,
                              category="Physical",
                              type="Grass"),
    "Night Daze": DamagingMove("Night Daze",
                              power=85,
                              category="Special",
                              type="Dark"),
    "Night Shade": DamagingMove("Night Shade",
                              power=0,
                              category="Special",
                              type="Ghost"),
    "Night Slash": DamagingMove("Night Slash",
                              power=70,
                              category="Physical",
                              type="Dark"),
    "Nuzzle": DamagingMove("Nuzzle",
                              power=20,
                              category="Physical",
                              type="Electric"),
    "Oblivion Wing": DamagingMove("Oblivion Wing",
                              power=80,
                              category="Special",
                              type="Flying"),
    "Octazooka": DamagingMove("Octazooka",
                              power=65,
                              category="Special",
                              type="Water"),
    "Ominous Wind": DamagingMove("Ominous Wind",
                              power=60,
                              category="Special",
                              type="Ghost"),
    "Origin Pulse": DamagingMove("Origin Pulse",
                              power=110,
                              category="Special",
                              type="Water"),
    "Outrage": DamagingMove("Outrage",
                              power=120,
                              category="Physical",
                              type="Dragon"),
    "Overheat": DamagingMove("Overheat",
                              power=130,
                              category="Special",
                              type="Fire"),
    "Parabolic Charge": DamagingMove("Parabolic Charge",
                              power=50,
                              category="Special",
                              type="Electric"),
    "Pay Day": DamagingMove("Pay Day",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Payback": DamagingMove("Payback",
                              power=50,
                              category="Physical",
                              type="Dark"),
    "Peck": DamagingMove("Peck",
                              power=35,
                              category="Physical",
                              type="Flying"),
    "Petal Blizzard": DamagingMove("Petal Blizzard",
                              power=90,
                              category="Physical",
                              type="Grass"),
    "Petal Dance": DamagingMove("Petal Dance",
                              power=120,
                              category="Special",
                              type="Grass"),
    "Phantom Force": DamagingMove("Phantom Force",
                              power=90,
                              category="Physical",
                              type="Ghost"),
    "Pin Missile": DamagingMove("Pin Missile",
                              power=25,
                              category="Physical",
                              type="Bug"),
    "Play Rough": DamagingMove("Play Rough",
                              power=90,
                              category="Physical",
                              type="Fairy"),
    "Pluck": DamagingMove("Pluck",
                              power=60,
                              category="Physical",
                              type="Flying"),
    "Poison Fang": DamagingMove("Poison Fang",
                              power=50,
                              category="Physical",
                              type="Poison"),
    "Poison Jab": DamagingMove("Poison Jab",
                              power=80,
                              category="Physical",
                              type="Poison"),
    "Poison Sting": DamagingMove("Poison Sting",
                              power=15,
                              category="Physical",
                              type="Poison"),
    "Poison Tail": DamagingMove("Poison Tail",
                              power=50,
                              category="Physical",
                              type="Poison"),
    "Pound": DamagingMove("Pound",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Powder Snow": DamagingMove("Powder Snow",
                              power=40,
                              category="Special",
                              type="Ice"),
    "Power Gem": DamagingMove("Power Gem",
                              power=80,
                              category="Special",
                              type="Rock"),
    "Power Whip": DamagingMove("Power Whip",
                              power=120,
                              category="Physical",
                              type="Grass"),
    "Power-Up Punch": DamagingMove("Power-Up Punch",
                              power=40,
                              category="Physical",
                              type="Fighting"),
    "Precipice Blades": DamagingMove("Precipice Blades",
                              power=120,
                              category="Physical",
                              type="Ground"),
    "Present": DamagingMove("Present",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Psybeam": DamagingMove("Psybeam",
                              power=65,
                              category="Special",
                              type="Psychic"),
    "Psychic": DamagingMove("Psychic",
                              power=90,
                              category="Special",
                              type="Psychic"),
    "Psycho Boost": DamagingMove("Psycho Boost",
                              power=140,
                              category="Special",
                              type="Psychic"),
    "Psycho Cut": DamagingMove("Psycho Cut",
                              power=70,
                              category="Physical",
                              type="Psychic"),
    "Psyshock": DamagingMove("Psyshock",
                              power=80,
                              category="Special",
                              type="Psychic"),
    "Psystrike": DamagingMove("Psystrike",
                              power=100,
                              category="Special",
                              type="Psychic"),
    "Psywave": DamagingMove("Psywave",
                              power=0,
                              category="Special",
                              type="Psychic"),
    "Punishment": DamagingMove("Punishment",
                              power=0,
                              category="Physical",
                              type="Dark"),
    "Pursuit": DamagingMove("Pursuit",
                              power=40,
                              category="Physical",
                              type="Dark"),
    "Quick Attack": DamagingMove("Quick Attack",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Rage": DamagingMove("Rage",
                              power=20,
                              category="Physical",
                              type="Normal"),
    "Rapid Spin": DamagingMove("Rapid Spin",
                              power=20,
                              category="Physical",
                              type="Normal"),
    "Razor Leaf": DamagingMove("Razor Leaf",
                              power=55,
                              category="Physical",
                              type="Grass"),
    "Razor Shell": DamagingMove("Razor Shell",
                              power=75,
                              category="Physical",
                              type="Water"),
    "Razor Wind": DamagingMove("Razor Wind",
                              power=80,
                              category="Special",
                              type="Normal"),
    "Relic Song": DamagingMove("Relic Song",
                              power=75,
                              category="Special",
                              type="Normal"),
    "Retaliate": DamagingMove("Retaliate",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Return": DamagingMove("Return",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Revenge": DamagingMove("Revenge",
                              power=60,
                              category="Physical",
                              type="Fighting"),
    "Reversal": DamagingMove("Reversal",
                              power=0,
                              category="Physical",
                              type="Fighting"),
    "Roar of Time": DamagingMove("Roar of Time",
                              power=150,
                              category="Special",
                              type="Dragon"),
    "Rock Blast": DamagingMove("Rock Blast",
                              power=25,
                              category="Physical",
                              type="Rock"),
    "Rock Climb": DamagingMove("Rock Climb",
                              power=90,
                              category="Physical",
                              type="Normal"),
    "Rock Slide": DamagingMove("Rock Slide",
                              power=75,
                              category="Physical",
                              type="Rock"),
    "Rock Smash": DamagingMove("Rock Smash",
                              power=40,
                              category="Physical",
                              type="Fighting"),
    "Rock Throw": DamagingMove("Rock Throw",
                              power=50,
                              category="Physical",
                              type="Rock"),
    "Rock Tomb": DamagingMove("Rock Tomb",
                              power=60,
                              category="Physical",
                              type="Rock"),
    "Rock Wrecker": DamagingMove("Rock Wrecker",
                              power=150,
                              category="Physical",
                              type="Rock"),
    "Rolling Kick": DamagingMove("Rolling Kick",
                              power=60,
                              category="Physical",
                              type="Fighting"),
    "Rollout": DamagingMove("Rollout",
                              power=30,
                              category="Physical",
                              type="Rock"),
    "Round": DamagingMove("Round",
                              power=60,
                              category="Special",
                              type="Normal"),
    "Sacred Fire": DamagingMove("Sacred Fire",
                              power=100,
                              category="Physical",
                              type="Fire"),
    "Sacred Sword": DamagingMove("Sacred Sword",
                              power=90,
                              category="Physical",
                              type="Fighting"),
    "Sand Tomb": DamagingMove("Sand Tomb",
                              power=35,
                              category="Physical",
                              type="Ground"),
    "Scald": DamagingMove("Scald",
                              power=80,
                              category="Special",
                              type="Water"),
    "Scratch": DamagingMove("Scratch",
                              power=40,
                              category="Physical",
                              type="Normal"),
    "Searing Shot": DamagingMove("Searing Shot",
                              power=100,
                              category="Special",
                              type="Fire"),
    "Secret Power": DamagingMove("Secret Power",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Secret Sword": DamagingMove("Secret Sword",
                              power=85,
                              category="Special",
                              type="Fighting"),
    "Seed Bomb": DamagingMove("Seed Bomb",
                              power=80,
                              category="Physical",
                              type="Grass"),
    "Seed Flare": DamagingMove("Seed Flare",
                              power=120,
                              category="Special",
                              type="Grass"),
    "Seismic Toss": DamagingMove("Seismic Toss",
                              power=0,
                              category="Physical",
                              type="Fighting"),
    "Self-Destruct": DamagingMove("Self-Destruct",
                              power=200,
                              category="Physical",
                              type="Normal"),
    "Shadow Ball": DamagingMove("Shadow Ball",
                              power=80,
                              category="Special",
                              type="Ghost"),
    "Shadow Claw": DamagingMove("Shadow Claw",
                              power=70,
                              category="Physical",
                              type="Ghost"),
    "Shadow Force": DamagingMove("Shadow Force",
                              power=120,
                              category="Physical",
                              type="Ghost"),
    "Shadow Punch": DamagingMove("Shadow Punch",
                              power=60,
                              category="Physical",
                              type="Ghost"),
    "Shadow Sneak": DamagingMove("Shadow Sneak",
                              power=40,
                              category="Physical",
                              type="Ghost"),
    "Sheer Cold": DamagingMove("Sheer Cold",
                              power=0,
                              category="Special",
                              type="Ice"),
    "Shock Wave": DamagingMove("Shock Wave",
                              power=60,
                              category="Special",
                              type="Electric"),
    "Signal Beam": DamagingMove("Signal Beam",
                              power=75,
                              category="Special",
                              type="Bug"),
    "Silver Wind": DamagingMove("Silver Wind",
                              power=60,
                              category="Special",
                              type="Bug"),
    "Skull Bash": DamagingMove("Skull Bash",
                              power=130,
                              category="Physical",
                              type="Normal"),
    "Sky Attack": DamagingMove("Sky Attack",
                              power=140,
                              category="Physical",
                              type="Flying"),
    "Sky Drop": DamagingMove("Sky Drop",
                              power=60,
                              category="Physical",
                              type="Flying"),
    "Sky Uppercut": DamagingMove("Sky Uppercut",
                              power=85,
                              category="Physical",
                              type="Fighting"),
    "Slam": DamagingMove("Slam",
                              power=80,
                              category="Physical",
                              type="Normal"),
    "Slash": DamagingMove("Slash",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Sludge": DamagingMove("Sludge",
                              power=65,
                              category="Special",
                              type="Poison"),
    "Sludge Bomb": DamagingMove("Sludge Bomb",
                              power=90,
                              category="Special",
                              type="Poison"),
    "Sludge Wave": DamagingMove("Sludge Wave",
                              power=95,
                              category="Special",
                              type="Poison"),
    "Smack Down": DamagingMove("Smack Down",
                              power=50,
                              category="Physical",
                              type="Rock"),
    "Smelling Salts": DamagingMove("Smelling Salts",
                              power=70,
                              category="Physical",
                              type="Normal"),
    "Smog": DamagingMove("Smog",
                              power=30,
                              category="Special",
                              type="Poison"),
    "Snarl": DamagingMove("Snarl",
                              power=55,
                              category="Special",
                              type="Dark"),
    "Snore": DamagingMove("Snore",
                              power=50,
                              category="Special",
                              type="Normal"),
    "Solar Beam": DamagingMove("Solar Beam",
                              power=120,
                              category="Special",
                              type="Grass"),
    "Sonic Boom": DamagingMove("Sonic Boom",
                              power=0,
                              category="Special",
                              type="Normal"),
    "Spacial Rend": DamagingMove("Spacial Rend",
                              power=100,
                              category="Special",
                              type="Dragon"),
    "Spark": DamagingMove("Spark",
                              power=65,
                              category="Physical",
                              type="Electric"),
    "Spike Cannon": DamagingMove("Spike Cannon",
                              power=20,
                              category="Physical",
                              type="Normal"),
    "Spit Up": DamagingMove("Spit Up",
                              power=0,
                              category="Special",
                              type="Normal"),
    "Steam Eruption": DamagingMove("Steam Eruption",
                              power=110,
                              category="Special",
                              type="Water"),
    "Steamroller": DamagingMove("Steamroller",
                              power=65,
                              category="Physical",
                              type="Bug"),
    "Steel Wing": DamagingMove("Steel Wing",
                              power=70,
                              category="Physical",
                              type="Steel"),
    "Stomp": DamagingMove("Stomp",
                              power=65,
                              category="Physical",
                              type="Normal"),
    "Stone Edge": DamagingMove("Stone Edge",
                              power=100,
                              category="Physical",
                              type="Rock"),
    "Stored Power": DamagingMove("Stored Power",
                              power=20,
                              category="Special",
                              type="Psychic"),
    "Storm Throw": DamagingMove("Storm Throw",
                              power=60,
                              category="Physical",
                              type="Fighting"),
    "Strength": DamagingMove("Strength",
                              power=80,
                              category="Physical",
                              type="Normal"),
    "Struggle": DamagingMove("Struggle",
                              power=50,
                              category="Physical",
                              type="Normal"),
    "Struggle Bug": DamagingMove("Struggle Bug",
                              power=50,
                              category="Special",
                              type="Bug"),
    "Submission": DamagingMove("Submission",
                              power=80,
                              category="Physical",
                              type="Fighting"),
    "Sucker Punch": DamagingMove("Sucker Punch",
                              power=80,
                              category="Physical",
                              type="Dark"),
    "Super Fang": DamagingMove("Super Fang",
                              power=0,
                              category="Physical",
                              type="Normal"),
    "Superpower": DamagingMove("Superpower",
                              power=120,
                              category="Physical",
                              type="Fighting"),
    "Surf": DamagingMove("Surf",
                              power=90,
                              category="Special",
                              type="Water"),
    "Swift": DamagingMove("Swift",
                              power=60,
                              category="Special",
                              type="Normal"),
    "Synchronoise": DamagingMove("Synchronoise",
                              power=120,
                              category="Special",
                              type="Psychic"),
    "Tackle": DamagingMove("Tackle",
                              power=50,
                              category="Physical",
                              type="Normal"),
    "Tail Slap": DamagingMove("Tail Slap",
                              power=25,
                              category="Physical",
                              type="Normal"),
    "Take Down": DamagingMove("Take Down",
                              power=90,
                              category="Physical",
                              type="Normal"),
    "Techno Blast": DamagingMove("Techno Blast",
                              power=120,
                              category="Special",
                              type="Normal"),
    "Thief": DamagingMove("Thief",
                              power=60,
                              category="Physical",
                              type="Dark"),
    "Thousand Arrows": DamagingMove("Thousand Arrows",
                              power=90,
                              category="Physical",
                              type="Ground"),
    "Thousand Waves": DamagingMove("Thousand Waves",
                              power=90,
                              category="Physical",
                              type="Ground"),
    "Thrash": DamagingMove("Thrash",
                              power=120,
                              category="Physical",
                              type="Normal"),
    "Thunder": DamagingMove("Thunder",
                              power=110,
                              category="Special",
                              type="Electric"),
    "Thunder Fang": DamagingMove("Thunder Fang",
                              power=65,
                              category="Physical",
                              type="Electric"),
    "Thunder Punch": DamagingMove("Thunder Punch",
                              power=75,
                              category="Physical",
                              type="Electric"),
    "Thunder Shock": DamagingMove("Thunder Shock",
                              power=40,
                              category="Special",
                              type="Electric"),
    "Thunderbolt": DamagingMove("Thunderbolt",
                              power=90,
                              category="Special",
                              type="Electric"),
    "Tri Attack": DamagingMove("Tri Attack",
                              power=80,
                              category="Special",
                              type="Normal"),
    "Triple Kick": DamagingMove("Triple Kick",
                              power=10,
                              category="Physical",
                              type="Fighting"),
    "Trump Card": DamagingMove("Trump Card",
                              power=0,
                              category="Special",
                              type="Normal"),
    "Twineedle": DamagingMove("Twineedle",
                              power=25,
                              category="Physical",
                              type="Bug"),
    "Twister": DamagingMove("Twister",
                              power=40,
                              category="Special",
                              type="Dragon"),
    "U-turn": DamagingMove("U-turn",
                              power=70,
                              category="Physical",
                              type="Bug"),
    "Uproar": DamagingMove("Uproar",
                              power=90,
                              category="Special",
                              type="Normal"),
    "V-create": DamagingMove("V-create",
                              power=180,
                              category="Physical",
                              type="Fire"),
    "Vacuum Wave": DamagingMove("Vacuum Wave",
                              power=40,
                              category="Special",
                              type="Fighting"),
    "Venoshock": DamagingMove("Venoshock",
                              power=65,
                              category="Special",
                              type="Poison"),
    "Vice Grip": DamagingMove("Vice Grip",
                              power=55,
                              category="Physical",
                              type="Normal"),
    "Vine Whip": DamagingMove("Vine Whip",
                              power=45,
                              category="Physical",
                              type="Grass"),
    "Vital Throw": DamagingMove("Vital Throw",
                              power=70,
                              category="Physical",
                              type="Fighting"),
    "Volt Switch": DamagingMove("Volt Switch",
                              power=70,
                              category="Special",
                              type="Electric"),
    "Volt Tackle": DamagingMove("Volt Tackle",
                              power=120,
                              category="Physical",
                              type="Electric"),
    "Wake-Up Slap": DamagingMove("Wake-Up Slap",
                              power=70,
                              category="Physical",
                              type="Fighting"),
    "Water Gun": DamagingMove("Water Gun",
                              power=40,
                              category="Special",
                              type="Water"),
    "Water Pledge": DamagingMove("Water Pledge",
                              power=80,
                              category="Special",
                              type="Water"),
    "Water Pulse": DamagingMove("Water Pulse",
                              power=60,
                              category="Special",
                              type="Water"),
    "Water Shuriken": DamagingMove("Water Shuriken",
                              power=15,
                              category="Physical",
                              type="Water"),
    "Water Spout": DamagingMove("Water Spout",
                              power=150,
                              category="Special",
                              type="Water"),
    "Waterfall": DamagingMove("Waterfall",
                              power=80,
                              category="Physical",
                              type="Water"),
    "Weather Ball": DamagingMove("Weather Ball",
                              power=50,
                              category="Special",
                              type="Normal"),
    "Whirlpool": DamagingMove("Whirlpool",
                              power=35,
                              category="Special",
                              type="Water"),
    "Wild Charge": DamagingMove("Wild Charge",
                              power=90,
                              category="Physical",
                              type="Electric"),
    "Wing Attack": DamagingMove("Wing Attack",
                              power=60,
                              category="Physical",
                              type="Flying"),
    "Wood Hammer": DamagingMove("Wood Hammer",
                              power=120,
                              category="Physical",
                              type="Grass"),
    "Wrap": DamagingMove("Wrap",
                              power=15,
                              category="Physical",
                              type="Normal"),
    "Wring Out": DamagingMove("Wring Out",
                              power=0,
                              category="Special",
                              type="Normal"),
    "X-Scissor": DamagingMove("X-Scissor",
                              power=80,
                              category="Physical",
                              type="Bug"),
    "Zap Cannon": DamagingMove("Zap Cannon",
                              power=120,
                              category="Special",
                              type="Electric"),
    "Zen Headbutt": DamagingMove("Zen Headbutt",
                              power=80,
                              category="Physical",
                              type="Psychic")
}
